spring.application.name=authentification

# database configuration
spring.datasource.url=jdbc:${DB_TYPE}://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# logging configuration
logging.level.root=INFO
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG

# configure jwt token.
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=${JWT_ACCESS_TOKEN_EXPIRATION}
security.jwt.refresh-time=${JWT_REFRESH_TOKEN_EXPIRATION}

# load all the environment variable from a .env file.
spring.config.import=optional:file:.env[.properties]
